# framework:
#     notifier:
#         chatter_transports:
#            teams: '%env(TEAMS_DSN)%'
#         #    telegram: '%env(TELEGRAM_DSN)%'
#         #texter_transports:
#         #    twilio: '%env(TWILIO_DSN)%'
#         #    nexmo: '%env(NEXMO_DSN)%'
#         channel_policy:
#             # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
#             urgent: ['email', 'teams']
#             high: ['email','teams']
#             medium: ['email','teams']
#             low: ['email','teams']
#         admin_recipients:
#             - { email: admin@example.com }
